---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-mlops-pub-tls
  namespace: harbor
spec:
  dnsNames:
  - harbor.mlops.pub
  - notary.mlops.pub
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns01
  secretName: harbor-mlops-pub-tls
