# This example demonstrates the ability to pass artifacts
# from one step to the next.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mnist-train-eval-
spec:
  entrypoint: mnist-controller
  templates:
  - name: mnist-controller
    steps:
    - - name: mnist-train
        template: train
    - - name: mnist-eval
        template: eval
        arguments:
          artifacts:
          - name: model-path
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"

  - name: train
    container:
      image: guoqiangqi/mnist-example:v1.0
      command: ['IS_TRAIN=True','python3']
      args: ["mnist_train_eval.py"]
    outputs:
      artifacts:
      - name: model-saved
        path: /mnist-example/ckpt
        gcs:
          bucket: mlops-example-bucket
          key: mnist-example-models
          serviceAccountKeySecret:
            name: mlops-bucket-serviceaccount
            key: serviceAccountKey

  - name: eval
    inputs:
      artifacts:
      - name: model-saved
        path: /mnist-example/ckpt
    container:
      image: alpine:latest
      command: ['IS_TRAIN=False','python3']
      args: ["mnist_train_eval.py"]
