# This example demonstrates the ability to pass artifacts
# from one step to the next.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mnist-train-eval-
spec:
  entrypoint: mnist-controller
  templates:
  - name: mnist-controller
    steps:
    - - name: mnist-train
        template: train
    - - name: mnist-eval
        template: eval
        arguments:
          artifacts:
          - name: model-path
            from: "{{steps.mnist-train.outputs.artifacts.model-saved}}"

  - name: train
    container:
      image: guoqiangqi/mnist-example:v1.0
      env:
      - name: IS_TRAIN
        value: "True"
      command: ['python3']
      args: ["mnist_train_eval.py"]
    outputs:
      artifacts:
      - name: model-saved
        path: /mnist-example/ckpt
        gcs:
          bucket: mlops-example-bucket
          key: mnist-example-models
          serviceAccountKeySecret:
            name: mlops-bucket-serviceaccount
            key: serviceAccountKey

  - name: eval
    inputs:
      artifacts:
      - name: model-path
        path: /mnist-example/ckpt
    container:
      image: guoqiangqi/mnist-example:v1.0
      env:
      - name: IS_TRAIN
        value: "False"
      command: ['python3']
      args: ["mnist_train_eval.py"]
