apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
  namespace: argo-events
spec:
  dependencies:
    - name: github-push
      eventSourceName: github
      eventName: github-push
  template:
    serviceAccountName: operate-workflow-sa
  triggers:
  - template:
      name: github-workflow-trigger
      k8s:
        operation: create
        parameters:
        - dest: spec.arguments.parameters.0.value
          src:
            dataKey: body.head_commit.id
            dependencyName: github-push
        - dest: spec.arguments.parameters.1.value
          src:
            dataKey: body.repository.url
            dependencyName: github-push
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: ci-workflow-
              namespace: argo
              labels:
                workflows.argoproj.io/workflow-template: ci-workflow
            spec:
              arguments:
                parameters:
                - name: head_commit_id
                - name: repository_url
                - name: app_repo
                  value: "MLops-Tools"
                - name: git_branch
                  value: 'main'
                - name: target_branch
                  value: 'main'
                - name: container_tag
                  value: 'latest'
                - name: container_image
                  value: "harbor.abu.pub/library/mnist-serving"
                - name: dockerfile
                  value: Dockerfile
                - name: path
                  value: "/workflows/examples/mnist-serving/docker/"
              workflowTemplateRef:
                name: ci-workflow
