apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-server-provisioner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nfs-server-provisioner
    server: 'https://kubernetes.default.svc'
  source:
    path: argo-workflows-ci-example/nfs-server-provisioner
    repoURL: 'https://github.com/TECH4DX/MLops-Tools.git'
    targetRevision: feature-integration
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=background
      - CreateNamespace=true