apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifest.yaml
- rolebinding.yml
- Ingress.yaml

patches:
- path: workflow-controller-configmap.yaml
  target:
    kind: ConfigMap
    name: workflow-controller-configmap
