apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  destination:
    namespace: postgresql
    server: 'https://kubernetes.default.svc'
  source:
    path: argo-workflows-ci-example/postgresql
    repoURL: 'https://github.com/TECH4DX/MLops-Tools.git'
    targetRevision: feature-integration
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=background
      - CreateNamespace=true