apiVersion: v1
data:
  config.json: |-
    {
        "auths": {
            "https://index.docker.io/v1/": {
                "auth": "=="
            }
        }
    }
kind: ConfigMap
metadata:
  name: docker-config
  namespace: argo
