apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-templates
  namespace: argocd
spec:
  destination:
    namespace: argo
    server: 'https://kubernetes.default.svc'
  source:
    path: bootstrap/workflow-templates
    repoURL: 'https://github.com/abuxliu/argo-workflows-ci-example.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=background
      - CreateNamespace=true