---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
  namespace: github-mnist
spec:
  service:
    ports:
      - name: github
        port: 12000
        targetPort: 12000
  github:
    github-push:
      repositories:
        - owner: guoqiangqi
          names:
            - webhook-test
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: https://github.mlops.pub
      events:
        - "push"
      apiToken:
        name: github-access
        key: token
      webhookSecret:
        name: github-access
        key: secret
      insecure: false
      active: true
      contentType: json
